#include <stdio.h>

/* ~~github/joseguilhermefmoura
 *
 * [PROBLEM:]
 *
 * 	 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *                                                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * [SOLUTION:]
 *
 *   Sum of the even-valued terms = 4613732.
 *
 * [MORE INFORMATION AT:]
 *
 *   https://projecteuler.net/problem=2
 *
 */

int main () {
	const int LIMIT = 4000000;
	int sumOfTheEvenValuedTerms = 0;
	int firstTerm = 1,  secondTerm = 1;
    int nextTerm = 0;
    
    while (secondTerm < LIMIT) {
        if (secondTerm % 2 == 0)
        	sumOfTheEvenValuedTerms += secondTerm;
        nextTerm   = firstTerm + secondTerm;
        firstTerm  = secondTerm;
        secondTerm = nextTerm;
    }
    
    printf("Sum of the even-valued terms = %d.\n", sumOfTheEvenValuedTerms);
	return 0;
}
